<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IFEL</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->asset('css/jquery.bxslider.css') ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/marquee.css') ?>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="<?= $this->asset('js/jquery.bxslider.js') ?>"></script>
    <script src="<?= $this->asset('js/marquee.js') ?>"></script>
    <style>
        body{padding:0;margin:0;overflow:hidden;background:url('<?= $this->asset('img/ledbg.png') ?>');color:#333;}
        span,img{float:left;}
        span{font-size:25px;margin:5px;}
        .score img{margin-top:8px;}
        .score {
            font-family: 'Major Mono Display', monospace;
            color:#fff;
            margin: 0px 0px 0px 5px;

        }
    </style>

    <script>
        $(document).ready(function(){
            $('.slider').bxSlider({
                auto: true,
                mode: 'fade',
                speed: 500,
                pause: 3000,
                autoHover: false,
                controls:false
            });
        });
        $(function (){
            let options = {
                autostart: true,
                property: 'value',
                onComplete: null,
                duration: 20000,
                padding: 50,
                marquee_class: '.marquee',
                container_class: '.simple-marquee-container',
                sibling_class: 0,
                hover: true,
                velocity: 0.03,
                direction: 'left'
            }
            $('.simple-marquee-container').SimpleMarquee(options);
            //$('.simple-marquee-container').SimpleMarquee();
        });
    </script>
</head>

<body style="padding:0;">

<!-- Stadium Big Screen -->

<div class="simple-marquee-container">
    <!--<div class="marquee-sibling">
        <div class="score" style="margin: 0px 0px 0px 10px;">
            <img src="<?= $this->asset('virtual-stadium/banner/team1.png');?>" style="width:25px;">
            <span>1</span><span>-</span><span>2</span>
            <img src="<?= $this->asset('virtual-stadium/banner/team2.png');?>"  style="width:25px;">
        </div>
    </div>-->
    <div class="marquee">
        <ul class="marquee-content-items">
            <li>Jelang Piala Menpora, Duo Brasil Arema Bakal Jalani Karantina di Jakarta</li>
            <li>Simon McMenemy Kembali ke Bhayangkara Solo FC</li>
            <li>Ghozali Siregar Mundur, Persib Sudah Kehilangan 5 Pemain Jelang Piala Menpora</li>
            <li>Dua Pemain Masih Menggantungkan Keputusan, Manajemen Arema FC Tidak Keberatan</li>
            <li>Belum Dapat yang Cocok, Arema Tak Paksakan Pakai Pelatih Asing di Piala Menpora 2021</li>
        </ul>
    </div>
</div>

<!-- Lobby Big Screen -->



</body>
</html>