<div class="col-12 col-lg-6">
    <div class="mc-col">
        <div class="mc-title border-0 m-0">
            <h2><?= ucwords($tournament->name) ?></h2>
        </div>
        <div class="row mb-4">
            <div class="col-12">
                <div class="ratio ratio-16x9 h-100">
                    <img src="<?= (empty($tournament->flag) ? $this->asset('/img/post/image-thumbnail.jpg') : $tournament->flag) ?>" class="card-img-top rounded-top" alt="...">
                </div>
            </div>
            <div class="col-12">
                <div class="top-bar bg-gray p-4 rounded-top">
                    <div class="ml-title">
                        <div class="ml-left">
                            <div class="label">
                                <span class="badge bg-primary px-3 rounded-pill"><?= ucwords($tournament->mode) ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-12">Pendaftaran dibuka:</div>
                            <div class="col-12 fw-bold mb-3">Sampai <?= date('d F Y H:i', strtotime($tournament->close_date) )  ?> WIB</div>
                        </div>
                        <div class="row">
                            <div class="col-12">Turnamen dimulai:</div>
                            <div class="col-12 fw-bold mb-3"> <?= date('d F Y H:i', strtotime($tournament->start_date) )  ?> WIB</div>
                        </div>
                        <div class="row">
                            <div class="col-12">Tim yang bergabung </div>
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="h3 fw-bold"><?= $tournament->teams_count ?>/<?= $tournament->open_slot ?></div>
                            </div>
                        </div>
                    </div>
                    <?php if($status_payment) :?>
                        <a href="<?= $this->router->to('siteTournamentEditTeam', ['id'=> $tournament->id])?>" class="btn btn-danger btn-lg w-100">Edit Team</a>
                    <?php elseif($tournament->is_private == 0) :?>
                        <a href="<?= $this->router->to('siteTournamentPayment', ['id'=> $tournament->id])?>" class="btn btn-success btn-lg w-100">
                            <div class="d-flex justify-content-between align-items-center py-2 px-3">
                                Join Tournament
                                <div class="d-flex align-items-center">
                                    <div class="rounded-pill text-center mb-0 me-2">
                                        <img src="<?=  $this->asset('img/icon/coin.svg')?>" width="18px" class="align-middle">
                                        <span><?= number_format($tournament->price)?></span>
                                    </div>
                                    <ion-icon name="chevron-forward-outline" class="md hydrated" role="img" aria-label="chevron forward outline"></ion-icon>
                                </div>
                            </div>
                        </a>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item bg-gray mb-3">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Detail Turnamen
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse border-0 collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <div class="top-bar">
                        <h5><?= $tournament->name ?></h5>
                        <div class="row">
                            <div class="col-4">Mode Turnamen</div>
                            <div class="col-8 fw-bold">: Single Elimination</div>
                        </div>
                        <div class="row">
                            <div class="col-4">Jenis Hadiah</div>
                            <div class="col-8 fw-bold">: Jumlah</div>
                        </div>
                        <div class="row">
                            <div class="col-4">Lokasi</div>
                            <div class="col-8 fw-bold">: Online Turnamen</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion-item bg-gray mb-3">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button text-primary collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Hadiah
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse border-0 collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <div class="top-bar">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="h5 fw-bold m-0">Rp<?= number_format($tournament->grand_prize)?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion-item bg-gray mb-3">
            <h2 class="accordion-header" id="headingFour">
                <button class="accordion-button text-primary collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    Deskripsi
                </button>
            </h2>
            <div id="collapseFour" class="accordion-collapse border-0 collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <div class="top-bar">
                        <?= $tournament->description ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>