<!DOCTYPE html>
<html lang="id">
<head>
    <?= $this->meta->head($meta['head']) ?>
    <?= $this->partial('shared/head') ?>
</head>
<body>
<?php
$this->partial('shared/header');
?>

<?= $this->partial('contact/single_content') ?>

<?= $this->partial('shared/footer') ?>
<?= $this->meta->foot($meta['foot']) ?>
<?= $this->partial('shared/foot') ?>

<?php if(module_exists('lib-recaptcha')): ?>
    <?php $sitekey = $this->config->libRecaptcha->sitekey; ?>
    <script src="https://www.google.com/recaptcha/api.js?render=<?= $sitekey ?>"></script>
    <script>
        let opts = {action: 'social'}
        grecaptcha.ready(() => {
            grecaptcha
                .execute('<?= $sitekey ?>', opts)
                .then(token => document.querySelector('#secure').value = token)
        });
    </script>

<?php endif; ?>
</body>
</html>