<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Match Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminMatch') ?>">Match</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?php
            $errors = $form->getErrors();
            ?>
            <?php if($errors): ?>
                <div class="alert alert-danger">
                    <strong><?= $error_message ?? 'Whoops!' ?></strong>
                    <ul>
                        <?php foreach($errors as $name => $error): ?>
                            <li>[<?= $name ?>] <?= $error->text ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <?= $form->csrfField('noob') ?>
            <div class="col-md-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('league', $leagues); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field('home_team', $team_option); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field('away_team', $team_option); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('match_date'); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('link'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('description'); ?>
                            </div>
                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>
</form>