<script src="<?= $this->asset('js/jquery-3.5.1.min.js') ?>"></script>
<script src="<?= $this->asset('js/bootstrap.bundle.min.js') ?>"></script>
<script src="<?= $this->asset('js/slick.min.js') ?>"></script>
<script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule="" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.js"></script>
<script src="<?= $this->asset('js/jquery.steps.min.js') ?>"></script>
<script src="<?= $this->asset('js/main.js').'?v='.date('Y-m-d-Hs') ?>"></script>