<main>
    <section class="main-container bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="mc-col">
                        <div class="mc-title flex-column align-items-start">
                            <h2>Success</h2>
                            <div class="mt-2 text-muted">Please click url that we sent to your email to reset your password.</div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</main>