
<main>
    <section class="main-container bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <div class="mc-col">
                        <div class="mc-title flex-column align-items-start">
                            <h2>Recovery Account</h2>
                            <div class="mt-2 text-muted">Please enter your identity ( email ) to identify your account.</div>
                            <?php if($error): ?>
                                <div class="alert alert-danger">
                                    <h2>Error</h2>
                                    <div><?=$error_message?></div>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="row mb-4 sponsorship-form">
                            <form method="POST">
                                <?= $form->csrfField('noob') ?>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="text" name="identity" required id="identity" placeholder="Email" class="form-control" value="<?= $this->req->getPost('identity') ?>" autofocus>
                                    </div>
                                </div>
                                <div class="col-12 col-lg-7">
                                    <button type="submit" class="btn btn-primary rounded-pill px-5">Reset</button>
                                </div>
                            </form>
                        </div>
                </div>
            </div>
        </div>
    </section>
</main>