<main>
    <section class="main-container bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="mc-col">
                        <div class="mc-title flex-column align-items-start">
                            <h2>Your Password Is Updated</h2>
                            <div class="mt-2 text-muted">Your password is updated, please login with your new password</div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
</main>