<main>
    <section class="main-container bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6 offset-lg-3">
                    <div class="mc-col">
                        <div class="row mb-4">
                            <div class="wizard-store" >
                                <h3 class="text-primary fw-bold">Konfirmasi Pembayaran</h3>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 99%;background-color: #198754;" aria-valuenow="99" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-lg-12">
                                        <div class="mt-2 mb-2 text-muted">Total Tagihan</div>
                                        <h5 class="mt-2 mb-3 text-warning">Rp <?= number_format($payment->amount) ?></h5>
                                    </div>
                                    <div class="col-12">
                                        <div class="accordion accordion-flush mb-3" id="accordionFlushExample">
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="flush-headingOne">
                                                    <button class="accordion-button collapsed ws-method" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                                                        <span><?= $payment->payment_method?></span>
                                                    </button>
                                                </h2>
                                                <div id="flush-collapseOne" class="accordion-collapse collapse show" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                                                    <div class="accordion-body text-secondary">

                                                        <?php if($payment->payment_method_code == 'QRIS') :?>
                                                        <div class="mb-3">QRIS</div>
                                                        <div class="d-flex align-items-center justify-content-between mb-3">
                                                            <div>
                                                                <img src="<?= $payment->pay_qrcode?>">
                                                            </div>
                                                        </div>
                                                        <?php else :?>
                                                        <div class="mb-3">Transfer Bank</div>
                                                        <div class="d-flex align-items-center justify-content-between mb-3">
                                                            <div>
                                                                <div>Nomor Rekening</div>
                                                                <div class="fw-bold"><?= $payment->pay_code ?></div>
                                                            </div>
                                                            <div>
                                                                <a href="#" class="copy-attr" data-copy="<?= $payment->pay_code ?>">Copy</a>
                                                            </div>
                                                        </div>
                                                        <?php endif;?>
                                                        <?php if($payment->net_amount != $payment->amount):?>
                                                        <div class="d-flex align-items-center justify-content-between mb-3">
                                                            <div>
                                                                <div>Biaya Admin:</div>
                                                                <div class="fw-bold">Rp <?= number_format($payment->surcharge) ?></div>
                                                            </div>
                                                        </div>
                                                        <?php endif; ?>
                                                        <div class="d-flex align-items-center justify-content-between mb-3">
                                                            <div>
                                                                <div>Total Tranfer:</div>
                                                                <div class="fw-bold">Rp <?= number_format($payment->amount) ?></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="alert alert-success">Harap melakukan Transfer ke rekening di atas sesuai dengan jumlah nominal yang tertera. <?php if(!isset($payment->tran_status) || $payment->tran_status == 'Diproses') :?> Lihat <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#paymentMethod">Cara Pembayaran</a><?php endif;?></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <?php if(!isset($payment->tran_status) || $payment->tran_status == 'Diproses') :?>
        <div class="modal fade" id="paymentMethod" tabindex="-1" role="dialog" aria-labelledby="paymentMethod" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-dark" id="exampleModalLabel">Payment Invoice</h5>
                        <button type="button" class="btn" data-bs-dismiss="modal" aria-label="Close">
                            <ion-icon name="close-outline" size="large"></ion-icon>
                        </button>
                    </div>
                    <div class="modal-body">
                        <iframe src="<?= $payment->snap_url ?>" style="height:400px" width="100%"></iframe>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </section>
</main>
