<!DOCTYPE html>
<html lang="id">
<head>
    <?= $this->meta->head($meta['head']) ?>
    <?= $this->partial('shared/head') ?>
</head>
<body>
<?php
$this->partial('shared/header');
?>

<main>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                    <?= $this->partial('profile/profile-section') ?>
                    <div class="mc-col">
                        <div class="mc-tabs">
                            <a href="<?= $this->router->to('siteProfileLiveMatch') ?>" class="active"><h2>Live Match</h2></a>
                            <a href="<?= $this->router->to('siteProfileNewsUpdate') ?>"><h2>News Update</h2></a>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <?php if(count($live_matches) > 0) :?>
                                    <?php foreach ($live_matches as $match):?>
                                        <a href="<?= $this->router->to('siteMatchSingle', ['id' => $match->id])?>" class="livematch-list">
                                            <div class="lm-left">
                                                <div class="text-center me-3">
                                                    <div class="btn btn-outline-danger rounded-pill py-0 mb-2">Live</div>
                                                    <div class="text-danger"><?= get_minute_diff($match->match_date) ?> Min</div>
                                                </div>
                                                <div class="lm-versus">
                                                    <div class="d-flex fw-bold">
                                                        <span class="text-primary">1</span>
                                                        <span><img src="<?= $match->home->flag ?>" width="20px" class="align-middle mx-2"></span>
                                                        <span class="lm-name"><?= $match->home->name ?></span>
                                                    </div>
                                                    <div class="d-flex fw-bold">
                                                        <span class="text-primary">3</span>
                                                        <span><img src="<?= $match->away->flag ?>" width="20px" class="align-middle mx-2"></span>
                                                        <span class="lm-name"><?= $match->away->name ?></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="lm-right">
                                                <div class="btn btn-primary rounded-pill">Virtual Stadion</div>
                                            </div>
                                        </a>
                                    <?php endforeach;?>
                                <?php else:?>
                                    <div class="text-center">
                                        <small>Currently there is no live match</small>
                                    </div>
                                <?php endif;?>
                            </div>
<!--                            <nav>-->
<!--                                <ul class="pagination justify-content-center">-->
<!--                                    <li class="page-item">-->
<!--                                        <a class="page-link" href="#" aria-label="Previous">-->
<!--                                            <span aria-hidden="true">&laquo;</span>-->
<!--                                        </a>-->
<!--                                    </li>-->
<!--                                    <li class="page-item"><a class="page-link active" href="#">1</a></li>-->
<!--                                    <li class="page-item"><a class="page-link" href="#">2</a></li>-->
<!--                                    <li class="page-item"><a class="page-link" href="#">3</a></li>-->
<!--                                    <li class="page-item">-->
<!--                                        <a class="page-link" href="#" aria-label="Next">-->
<!--                                            <span aria-hidden="true">&raquo;</span>-->
<!--                                        </a>-->
<!--                                    </li>-->
<!--                                </ul>-->
<!--                            </nav>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<?= $this->partial('shared/footer') ?>
<?= $this->meta->foot($meta['foot']) ?>
<?= $this->partial('shared/foot') ?>
</body>
</html>