<main>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                    <div class="mc-col py-4 m-0">
                        <div class="mc-title align-items-center border-0 m-0">
                            <a href="<?= $this->router->to('siteMatchSingle', ['id'=> $match->id]) ?>" class="btn text-primary position-absolute"><ion-icon name="arrow-back-outline" size="large"></ion-icon></a>
                            <h2 style="flex-basis: 100%;text-align: center;">Quiz: </h2>
                        </div>
                    </div>
                    <div class="mc-col">
                        <form method="post" id="quiz-form">
                            <?= $form->csrfField('noob') ?>
                            <input type="hidden" name="match_id" value="<?= $match->id?>">
                        <div id="quiz-bronze">
                            <?php foreach($question as $key => $q) :?>
                            <h3 class="text-muted">Pertanyaan <?= $key +1 ?></h3>
                            <section>
                                <div class="row align-items-center justify-content-center">
                                    <div class="col-5 col-lg-3">
                                        <div style="height: 50px;">Home</div>
                                        <div class="">
                                            <img src="<?= $match->home->flag ?>" style="width: 100px;height: auto;">
                                        </div>
                                        <div style="height: 50px;"><?= $match->home->name ?></div>
                                    </div>
                                    <div class="col-2 col-lg-2">
                                        vs
                                    </div>
                                    <div class="col-5 col-lg-3">
                                        <div style="height: 50px;">Away</div>
                                        <div class="">
                                            <img src="<?= $match->away->flag ?>" style="width: 100px;height: auto;">
                                        </div>
                                        <div style="height: 50px;"><?= $match->away->name ?></div>
                                    </div>
                                </div>
                                <h5><?= $q->question ?></h5>
                                <?php if($q->option_type == 1):?>
                                    <div>
                                        <?php foreach($q->options as $key => $option) :?>
                                        <div class="form-check p-0">
                                            <input class="form-check-input" type="radio" name="answer[<?=$q->id?>]" value="<?=$key?>" id="answer-<?=$q->id?>-<?=$key?>">
                                            <label class="form-check-label" for="answer-<?=$q->id?>-<?=$key?>">
                                                <?= $option ?>
                                            </label>
                                        </div>
                                        <?php endforeach; ?>
                                        <small class="text-muted">*Jawaban tidak dapat dirubah</small>
                                    </div>
                                <?php elseif($q->option_type == 2) :?>
                                    <div>
                                        <div class="row">
                                            <div class="col-6">
                                                <?php foreach($match->home->in_game_players as $key=> $player):?>
                                                <div class="form-check p-0">
                                                    <input class="form-check-input quiz-player-home-input d-none" type="radio" name="answer[<?= $q->id ?>][home][]" value="<?=$player->id?>" id="player-home-<?= $q->id.'-'.$player->id ?>">
                                                    <label class="form-check-label quiz-player-home-label" for="player-home-<?= $q->id.'-'.$player->id ?>">
                                                        <?= $player->name ?>
                                                    </label>
                                                </div>
                                                <?php endforeach; ?>
                                            </div>
                                            <div class="col-6">
                                                <?php foreach($match->away->in_game_players as $key=> $player):?>
                                                    <div class="form-check p-0">
                                                        <input class="form-check-input quiz-player-away-input d-none" type="radio" name="answer[<?= $q->id ?>][away][]" value="<?=$player->id?>" id="player-away-<?= $q->id.'-'.$player->id ?>">
                                                        <label class="form-check-label quiz-player-away-label" for="player-away-<?= $q->id.'-'.$player->id ?>">
                                                            <?= $player->name ?>
                                                        </label>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                        <small class="text-muted">*Jawaban tidak dapat dirubah</small>
                                    </div>
                                <?php elseif($q->option_type == 3) :?>
                                    <div class="form-quiz-gold">

                                        <div class="input-group justify-content-center mb-3">
                                            <span class="p-3">
                                                <input type="number" name="answer[<?=$q->id?>][home]" aria-label="First name" class="form-control d-block" placeholder="Home" style="height: 50px">
                                            </span>
                                            <span class="input-group-text bg-transparent border-0">VS</span>
                                            <span class="p-3">
                                                <input type="number" name="answer[<?=$q->id?>][away]" aria-label="name" class="form-control d-block" placeholder="Away" style="height: 50px">
                                            </span>
                                        </div>

                                        <small class="text-muted">*Jawaban tidak dapat dirubah</small>
                                    </div>
                                <?php endif; ?>
                            </section>
                            <?php endforeach; ?>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>