<!DOCTYPE html>
<html lang="id">
<head>
    <?= $this->meta->head($meta['head']) ?>
    <?= $this->partial('shared/head') ?>
</head>
<body>
<?php
$this->partial('shared/header');
?>

<main>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8">
                    <div class="mc-col py-5 m-0">
                        <div class="mc-title flex-column align-items-start border-0">
                            <h2>Create Account</h2>
                            <?php
                            $errors = $form->getErrors();
                            ?>
                            <?php if($errors): ?>
                                <div class="alert alert-danger">
                                    <strong><?= $error_message ?? 'Whoops!' ?></strong>
                                    <ul>
                                        <?php foreach($errors as $name => $error): ?>
                                            <li>[<?= $name ?>] <?= $error->text ?></li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="row auth-form">
                            <form method="POST">
                                <?= $form->csrfField('noob') ?>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="text" class="form-control" placeholder="Name*" name="name" value="<?= $this->req->getPost('name') ?>">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="email" class="form-control" placeholder="Email Address*" value="<?= $this->req->getPost('email') ?>">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="number" class="form-control" placeholder="Phone Number*" value="<?= $this->req->getPost('phone') ?>">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="text" class="datepicker form-control" placeholder="Date of birth*" value="<?= $this->req->getPost('birthdate') ?>">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="password" class="form-control" placeholder="Password*">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <input type="password" name="confirm_password" class="form-control" id="confirmpassword" placeholder="Confirm Password" required>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="cta">
                                        <button type="submit" class="btn btn-primary rounded-pill px-5">Sign up</button>
                                        <div class="cta-socmed">
                                            <div class="label">Or sign in with</div>
                                            <div class="social-media mb-0">
                                                <a href="#" class="bg-circle"><ion-icon name="logo-facebook" size="large"></ion-icon></a>
                                                <a href="#" class="bg-circle"><ion-icon name="logo-google" size="large"></ion-icon></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php if(module_exists('lib-recaptcha')): ?>
                                    <input type="hidden" name="secure" id="secure">
                                <?php endif; ?>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4 bg-light">
                    <div class="mc-col text-center py-5 m-0">
                        <div class="mc-title justify-content-center border-0">
                            <h2 class="text-center">Welcome back!</h2>
                        </div>
                        <p class="text-secondary">Login to your account to keep updated with our latest news and tournaments!</p>
                        <a href="<?= $this->router->to('siteLogin') ?>" class="btn btn-outline-primary rounded-pill px-4">Sign In</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<?= $this->partial('shared/footer') ?>
<?= $this->meta->foot($meta['foot']) ?>
<?= $this->partial('shared/foot') ?>
</body>
</html>