<!DOCTYPE html>
<html lang="id">
<head>
    <?= $this->meta->head($meta['head']) ?>
    <?= $this->partial('shared/head') ?>
</head>
<body>
<?php
$this->partial('shared/header');
?>

<?= $content ?>

<?= $this->partial('shared/footer') ?>
<?= $this->meta->foot($meta['foot']) ?>
<?= $this->partial('shared/foot') ?>
</body>

<script>
$(document).ready(function () {
    $('.gamesCard').click(function () {
        var id = $(this).attr('data-id');
        var base_url = window.location.origin;
        $.get(base_url+'/games/'+id,
        function (url) { window.location.href = url; });
    })
})
</script>
</html>