<main>
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                    <div class="mc-col">
                        <?= $this->partial('league/sticky-menu') ?>
                        <div class="mc-title">
                            <h2>Top Player at The Moment</h2>
                        </div>
                        <div class="mc-col">
                            <div class="top-player">
                                <div class="row">
                                    <div class="col-6 col-lg-4">
                                        <div class="tp-li">
                                            <a href="#" class="bg-red">
                                                <div class="status">
                                                    <div class="title">Top Scorer</div>
                                                    <div class="score">6</div>
                                                </div>
                                                <div class="photo">
                                                    <img src="assets/img/players/player-7.png">
                                                </div>
                                                <div class="player-name"><img src="assets/img/icon/icon-top.png"> Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="tp-li">
                                            <a href="#" class="bg-blue-g">
                                                <div class="status">
                                                    <div class="title">Top Assists Provider</div>
                                                    <div class="score">4</div>
                                                </div>
                                                <div class="photo">
                                                    <img src="assets/img/players/player-6.png">
                                                </div>
                                                <div class="player-name"><img src="assets/img/icon/icon-top.png"> Kilzyou</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="tp-li">
                                            <a href="#" class="bg-gold">
                                                <div class="status">
                                                    <div class="title">Best Defensive Player</div>
                                                    <div class="score">3679</div>
                                                </div>
                                                <div class="photo">
                                                    <img src="assets/img/players/player-5.png">
                                                </div>
                                                <div class="player-name"><img src="assets/img/icon/icon-top.png"> RoksaCzv22</div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end col -->
                        <div class="mc-title">
                            <h2>Player Stats</h2>
                        </div>
                        <div class="mc-col">
                            <div class="stat-player">
                                <div class="row">
                                    <div class="col-6 col-lg-4">
                                        <div class="sp-li">
                                            <a href="#" class="bg-gray-g">
                                                <div class="status">
                                                    <div class="title">Assists</div>
                                                    <div class="score">7</div>
                                                </div>
                                                <div class="player-name">Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="sp-li">
                                            <a href="#" class="bg-gray-g">
                                                <div class="status">
                                                    <div class="title">Assists</div>
                                                    <div class="score">5</div>
                                                </div>
                                                <div class="player-name">Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="sp-li">
                                            <a href="#" class="bg-gray-g">
                                                <div class="status">
                                                    <div class="title">Assists</div>
                                                    <div class="score">5</div>
                                                </div>
                                                <div class="player-name">Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="sp-li">
                                            <a href="#" class="bg-gray-g">
                                                <div class="status">
                                                    <div class="title">Shots</div>
                                                    <div class="score">11</div>
                                                </div>
                                                <div class="player-name">Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="sp-li">
                                            <a href="#" class="bg-gray-g">
                                                <div class="status">
                                                    <div class="title">Shots</div>
                                                    <div class="score">11</div>
                                                </div>
                                                <div class="player-name">Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <div class="sp-li">
                                            <a href="#" class="bg-gray-g">
                                                <div class="status">
                                                    <div class="title">Shots on Target</div>
                                                    <div class="score">9</div>
                                                </div>
                                                <div class="player-name">Alexr</div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end col -->
                        <div class="mc-title">
                            <h2>Club Stats</h2>
                        </div>
                        <div class="mc-col">
                            <div class="stat-club">
                                <div class="row">
                                    <div class="col-12 col-lg-4">
                                        <div class="sc-li">
                                            <a href="#" class="bg-gray">
                                                <div class="club-desc">
                                                    <div class="status">
                                                        <div class="title">Wins</div>
                                                        <div class="score">3</div>
                                                    </div>
                                                    <div class="player-name">FC Bayern Muenchen</div>
                                                </div>
                                                <div class="club-img bg-red">
                                                    <img src="assets/img/flag/1200px-Logo_FC_Bayern_München_(2002–2017).svg.png">
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-4">
                                        <div class="sc-li">
                                            <a href="#" class="bg-gray">
                                                <div class="club-desc">
                                                    <div class="status">
                                                        <div class="title">Goal Scored</div>
                                                        <div class="score">10</div>
                                                    </div>
                                                    <div class="player-name">Chelsea FC</div>
                                                </div>
                                                <div class="club-img bg-blue-g">
                                                    <img src="assets/img/flag/rgb-mar18.png">
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-4">
                                        <div class="sc-li">
                                            <a href="#" class="bg-gray">
                                                <div class="club-desc">
                                                    <div class="status">
                                                        <div class="title">Goal Scored</div>
                                                        <div class="score">10</div>
                                                    </div>
                                                    <div class="player-name">Arsenal</div>
                                                </div>
                                                <div class="club-img bg-gold">
                                                    <img src="assets/img/flag/logo-arsenal.svg">
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-4">
                                        <div class="sc-li">
                                            <a href="#" class="bg-gray">
                                                <div class="club-desc">
                                                    <div class="status">
                                                        <div class="title">Assists</div>
                                                        <div class="score">9</div>
                                                    </div>
                                                    <div class="player-name">FC Bayern Muenchen</div>
                                                </div>
                                                <div class="club-img bg-red">
                                                    <img src="assets/img/flag/1200px-Logo_FC_Bayern_München_(2002–2017).svg.png">
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-4">
                                        <div class="sc-li">
                                            <a href="#" class="bg-gray">
                                                <div class="club-desc">
                                                    <div class="status">
                                                        <div class="title">Shots</div>
                                                        <div class="score">30</div>
                                                    </div>
                                                    <div class="player-name">FC Bayern Muenchen</div>
                                                </div>
                                                <div class="club-img bg-red">
                                                    <img src="assets/img/flag/1200px-Logo_FC_Bayern_München_(2002–2017).svg.png">
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-4">
                                        <div class="sc-li">
                                            <a href="#" class="bg-gray">
                                                <div class="club-desc">
                                                    <div class="status">
                                                        <div class="title">Shots on Target</div>
                                                        <div class="score">23</div>
                                                    </div>
                                                    <div class="player-name">FC Bayern Muenchen</div>
                                                </div>
                                                <div class="club-img bg-red">
                                                    <img src="assets/img/flag/1200px-Logo_FC_Bayern_München_(2002–2017).svg.png">
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end col -->
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>