
<main>
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                    <div class="mc-col">
                        <?= $this->partial('league/sticky-menu') ?>
                        <div class="mc-title">
                            <h2>About</h2>
                        </div>
                        <div class="mc-content">
                            <?= $league->description ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>